### PR TITLE
Language / Text

### PR DESCRIPTION
**Pull request by mrmoo85**
Changed language / text of the web UI because I found it confusing.

discuss merge :)

### CODE REVIEW

**Comment by MoneroOcean** [comment]
Thanks!

**Comment by mrmoo85** [comment]
No problemo. I fixed it for myself but figured might as well submit it :)

I was considering learning enough NodeJS to add in a column that shows what port the miner is connected to. Just for diagnostics :) Feel free to beat me to it :P

Thanks for the changes to the proxy, love the web UI.

**Comment by djfinch** [comment]
Thanks. It was caused by me. I forgot on my modified MomentJS which showing fields as (example) Share ago : ~min, Ping ago : ~sec, and so on... Reason for this was minimizing table fields lenght and make whole table more 'compact'. But yes, unmodified MomentJS output looks a bit weird with this...

**Comment by MoneroOcean** [comment]
@mrmoo85 it is better to add this as tooltip to avoid table overload. Please take your time to learn nodejs and do PR :)

**Comment by mrmoo85** [comment]
@MoneroOcean, you said "Thanks" and merged it... I am now getting mixed signals O-o

You could be a little more pleasant like you were initially - not saying "please take your time to learn nodejs" after I already told you I do not know NodeJS, and I only changed the text (no code, check the request) and therefore do not need to know NodeJS to know English.

Table header as "Ping Ago" makes no sense in English, or it is confusing (read the OP and the merge source)

People on GitHub are assholes. Forget working for any open source anything... Even shit I know how to code everyone I run into on here is an asshole.

Good luck when you and other GH users like to alienate other contributers (***after merging the code this time***)

Just reverse the merge and next time deny the request instead of accepting it, thanking the person, and then making them feel like shit for contributing (however small it was in this instance)

I think I will keep my source on private Git. Fuck GH don't need a portfolio here. I can just host it myself privately.

I am out. Good Day (unsubscribed)

**Comment by MoneroOcean** [comment]
Hm, you are definitely overreacting. I merged your PR since it was OK and I just reassured that I can wait for your next PR just fine since you mentioned that you need to learn nodejs yourself.

But yes, I agree open source community can be harsh (not me in this situation in which you misunderstood my intention) and it is better to grow some thick skin if you consider to return.

**Pull request merged**
