### PR TITLE
Link to MO dashboard.

### PR DESCRIPTION
**Pull request by djfinch**
If activePool is "moneroocean" and "moDashboard" in config is set to "true" then pool header in dashboard is "clickable" and pointing to "https://moneroocean.stream/#/dashboard?addr=walletID".

This time I checked everything but please can you x-check, too?

### CODE REVIEW

**Comment by MoneroOcean** [comment]
I will apply this and will remove moDashboard config variable since I think URL check that you already have will be enough.

**Comment by MoneroOcean** [comment]
And thanks for improvement!

**Comment by djfinch** [comment]
Okay, thank you. You're welcome. I thought that someone want to disable this as walletID is sent as part of url so can be seen on resolver, history or so... But you're the boss.. :)

**Comment by MoneroOcean** [comment]
Hm, not thought about that. Do you think it is a serious potential privacy issue? Can it happen if you do not click this link?

**Comment by djfinch** [comment]
I don't know. Not a big privacy flaw, I guess. It's a bit problematic if someone bind httpAddress to 0.0.0.0 and using, for example, AWS ... so dashboard is then accessible to everyone. And that's their business...  I'm still thinking about config editor + restart proxy button in dashboard but accessControl:enabled:true should be mandatory then.

**Pull request merged**
