### PR TITLE
Fix activePools[this.pool] undefined

### PR DESCRIPTION
**Pull request by bobbieltd**
I still don't understand why it happens. If you think it is unnecessary, do not merge.

### CODE REVIEW

**Comment by MoneroOcean** [comment]
What happens? Can you copy paste failure stack?

**Comment by bobbieltd** [comment]
Just my guess. What will happen when proxy have a port with coin xyz but there is no pool with coin xyz (I know it is weird like that) ?

**Comment by MoneroOcean** [comment]
No idea. As you noticed I almost removed coin support from my proxy in favor of more flexible algo/blob_type options.

**Comment by bobbieltd** [comment]
It is irrational to have this error. It happens when you have miners wihout pools supporting these miners. I have not merge your algo/blob_type because I’m worried about forknote blob_type incompatibility. I’ll consider it later. Closing PR.

**Pull request closed without merging**
