### PR TITLE
qrl support

### PR DESCRIPTION
**Pull request by untoreh**

### CODE REVIEW

**Comment by untoreh** [comment]
no they skip cnutils blob conversion

**Comment by untoreh** [comment]
if you specify the blob_type it means you know it and want to use it, if you want to use the original just don't write it in the pool config

**Comment by bobbieltd** [comment]
The pool owner will know better than miners what blob_type for the coin.
I doubt that miners understand what blob_type is, they often use “try and fail” method.
Blob_type is too technical and we should prefer pool’s choice to miner’s choice.

**Comment by untoreh** [comment]
rebased

**Pull request closed without merging**
